"""Declarative base, naming conventions and shared column mixins.

Everything that every table needs — the metadata object Alembic diffs against,
deterministic constraint names, UUID primary keys and timestamp columns — lives
here so that no model has to restate it.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention for every implicitly created constraint and index.
# Without it PostgreSQL invents names, autogenerated migrations disagree with
# the live schema, and a constraint can only be dropped by looking it up first.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for every ORM model.

    ``Base.metadata`` is the single source of truth for the schema and is what
    ``alembic/env.py`` compares the database against.
    """

    metadata = metadata


class UUIDPrimaryKeyMixin:
    """A random UUID primary key.

    Surrogate integer keys are deliberately avoided for the main entities: a
    sequential id leaks how many reports exist and in what order they arrived,
    which is metadata a whistleblowing system should not publish. The default
    is generated by PostgreSQL (``gen_random_uuid()``, built in since 13) so
    rows inserted outside the ORM — by a migration or by hand — are still
    well-formed.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        # Mixin columns are appended after the model's own by default;
        # sort_order puts the key first and the timestamps last, so the
        # physical column order matches how the table reads.
        sort_order=-100,
    )


class CreatedAtMixin:
    """An immutable creation timestamp, stored timezone-aware in UTC."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        sort_order=100,
    )


class TimestampMixin(CreatedAtMixin):
    """Creation and last-modification timestamps.

    ``updated_at`` is maintained by SQLAlchemy's ``onupdate`` rather than by a
    database trigger. That keeps the schema portable and trigger-free; the
    trade-off is that an UPDATE issued outside the ORM will not refresh it.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        sort_order=101,
    )
